version: "3.8"
services:
  redis:
    image: redis:7
    container_name: surgitrack-redis
    ports:
      - "6379:6379"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    ports:
      - "8000:8000"
    environment:
      - GOOGLE_GEMINI_API_KEY=${GOOGLE_GEMINI_API_KEY}
      - REDIS_URL=redis://redis:6379
    volumes:
      - ./backend/chroma_langchain_db:/app/chroma_langchain_db
    depends_on:
      - redis

  worker:
    build:
      context: .
      dockerfile: backend/Dockerfile
    command: python worker.py
    depends_on:
      - redis
    environment:
      - REDIS_URL=redis://redis:6379

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
